CREATE TABLE TB_EMPRESA(
ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
NOME_FANTASIA VARCHAR(150) NOT NULL,
UF VARCHAR(2) NOT NULL,
DOCUMENTO BIGINT NOT NULL,
DATA_CADASTRO DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE TB_FORNECEDOR(
ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
NOME VARCHAR(150) NOT NULL,
EMAIL VARCHAR(200) NOT NULL,
CPF_CNPJ BIGINT NOT NULL,
RG BIGINT,
DATA_NASCIMENTO DATETIME2,
DATA_CADASTRO DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE TB_EMPRESA_FORNECEDOR(
ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
ID_EMPRESA UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES TB_EMPRESA(ID) ON DELETE CASCADE,
ID_FORNECEDOR UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES TB_FORNECEDOR(ID) ON DELETE CASCADE,
DATA_CADASTRO DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP
)